/**
 * Curated list of common crops and permaculture plants for Romania.
 * Used by: PermaculturePlanWizard, AI payload, plant selector, future seed scripts.
 *
 * English `name` values are stable internal identifiers.
 * `labelRo` provides the Romanian display label.
 * Priority: 1 = most common, 2 = common, 3 = less common / regional.
 */

export const MAIN_CROPS_ROMANIA = [
    // ── Vegetables ────────────────────────────────────────────────────────────
    {
        name: 'Tomato',
        labelRo: 'Roșii',
        category: 'fruiting_vegetable',
        group: 'Vegetables',
        priority: 1,
        commonInRomania: true,
        season: 'Summer–Autumn',
        sunlight: 'Full Sun',
        waterNeeds: 'Medium',
        rootDepth: 'Medium',
        perennial: false,
        guildRole: ['Producer'],
        ecologicalFunctions: ['Food production'],
        companionNotes: 'Good with basil, marigold, onion, garlic, carrot.',
    },
    {
        name: 'Pepper',
        labelRo: 'Ardei',
        category: 'fruiting_vegetable',
        group: 'Vegetables',
        priority: 1,
        commonInRomania: true,
        season: 'Summer–Autumn',
        sunlight: 'Full Sun',
        waterNeeds: 'Medium',
        rootDepth: 'Medium',
        perennial: false,
        guildRole: ['Producer'],
        ecologicalFunctions: ['Food production'],
        companionNotes: 'Good with basil, onion, carrot, parsley.',
    },
    {
        name: 'Eggplant',
        labelRo: 'Vinete',
        category: 'fruiting_vegetable',
        group: 'Vegetables',
        priority: 1,
        commonInRomania: true,
        season: 'Summer',
        sunlight: 'Full Sun',
        waterNeeds: 'Medium',
        rootDepth: 'Medium',
        perennial: false,
        guildRole: ['Producer'],
        ecologicalFunctions: ['Food production'],
        companionNotes: 'Good with beans, basil, marigold.',
    },
    {
        name: 'Cucumber',
        labelRo: 'Castraveți',
        category: 'fruiting_vegetable',
        group: 'Vegetables',
        priority: 1,
        commonInRomania: true,
        season: 'Summer',
        sunlight: 'Full Sun',
        waterNeeds: 'High',
        rootDepth: 'Shallow',
        perennial: false,
        guildRole: ['Producer'],
        ecologicalFunctions: ['Food production', 'Vertical crop'],
        companionNotes: 'Good with dill, beans, corn, radish, sunflower.',
    },
    {
        name: 'Zucchini',
        labelRo: 'Dovlecel',
        category: 'fruiting_vegetable',
        group: 'Vegetables',
        priority: 1,
        commonInRomania: true,
        season: 'Summer',
        sunlight: 'Full Sun',
        waterNeeds: 'Medium',
        rootDepth: 'Medium',
        perennial: false,
        guildRole: ['Producer'],
        ecologicalFunctions: ['Food production', 'Ground cover'],
        companionNotes: 'Good with nasturtium, borage, corn, beans.',
    },
    {
        name: 'Pumpkin',
        labelRo: 'Dovleac',
        category: 'vine',
        group: 'Vegetables',
        priority: 2,
        commonInRomania: true,
        season: 'Summer–Autumn',
        sunlight: 'Full Sun',
        waterNeeds: 'Medium',
        rootDepth: 'Medium',
        perennial: false,
        guildRole: ['Producer', 'Groundcover'],
        ecologicalFunctions: ['Food production', 'Living mulch'],
        companionNotes: 'Good in Three Sisters with corn and beans.',
    },
    {
        name: 'Bean',
        labelRo: 'Fasole',
        category: 'legume',
        group: 'Vegetables',
        priority: 1,
        commonInRomania: true,
        season: 'Summer',
        sunlight: 'Full Sun',
        waterNeeds: 'Medium',
        rootDepth: 'Medium',
        perennial: false,
        guildRole: ['Producer', 'Nitrogen fixer'],
        ecologicalFunctions: ['Food production', 'Nitrogen fixation'],
        companionNotes: 'Good with corn, pumpkin, cucumber, savory.',
    },
    {
        name: 'Pea',
        labelRo: 'Mazăre',
        category: 'legume',
        group: 'Vegetables',
        priority: 2,
        commonInRomania: true,
        season: 'Spring',
        sunlight: 'Full Sun',
        waterNeeds: 'Medium',
        rootDepth: 'Shallow',
        perennial: false,
        guildRole: ['Producer', 'Nitrogen fixer'],
        ecologicalFunctions: ['Food production', 'Nitrogen fixation'],
        companionNotes: 'Good before summer crops such as tomatoes or peppers.',
    },
    {
        name: 'Corn',
        labelRo: 'Porumb',
        category: 'grain',
        group: 'Vegetables',
        priority: 2,
        commonInRomania: true,
        season: 'Summer',
        sunlight: 'Full Sun',
        waterNeeds: 'Medium',
        rootDepth: 'Medium',
        perennial: false,
        guildRole: ['Producer', 'Support'],
        ecologicalFunctions: ['Food production', 'Trellis/support crop'],
        companionNotes: 'Good with beans and pumpkin.',
    },
    {
        name: 'Potato',
        labelRo: 'Cartofi',
        category: 'root_crop',
        group: 'Vegetables',
        priority: 1,
        commonInRomania: true,
        season: 'Spring–Summer',
        sunlight: 'Full Sun',
        waterNeeds: 'Medium',
        rootDepth: 'Medium',
        perennial: false,
        guildRole: ['Producer'],
        ecologicalFunctions: ['Food production'],
        companionNotes: 'Avoid planting near tomatoes and eggplants because they share disease risks.',
    },

    // ── Roots & Bulbs ─────────────────────────────────────────────────────────
    {
        name: 'Carrot',
        labelRo: 'Morcovi',
        category: 'root_crop',
        group: 'Roots & Bulbs',
        priority: 1,
        commonInRomania: true,
        season: 'Spring–Autumn',
        sunlight: 'Full Sun',
        waterNeeds: 'Medium',
        rootDepth: 'Deep',
        perennial: false,
        guildRole: ['Producer'],
        ecologicalFunctions: ['Food production', 'Root crop'],
        companionNotes: 'Good with onion, leek, lettuce, tomato.',
    },
    {
        name: 'Parsley Root',
        labelRo: 'Pătrunjel rădăcină',
        category: 'root_crop',
        group: 'Roots & Bulbs',
        priority: 1,
        commonInRomania: true,
        season: 'Spring–Autumn',
        sunlight: 'Full Sun',
        waterNeeds: 'Medium',
        rootDepth: 'Deep',
        perennial: false,
        guildRole: ['Producer'],
        ecologicalFunctions: ['Food production'],
        companionNotes: 'Common Romanian soup vegetable.',
    },
    {
        name: 'Celery Root',
        labelRo: 'Țelină',
        category: 'root_crop',
        group: 'Roots & Bulbs',
        priority: 2,
        commonInRomania: true,
        season: 'Summer–Autumn',
        sunlight: 'Full Sun',
        waterNeeds: 'High',
        rootDepth: 'Medium',
        perennial: false,
        guildRole: ['Producer'],
        ecologicalFunctions: ['Food production'],
        companionNotes: 'Needs rich soil and regular moisture.',
    },
    {
        name: 'Beetroot',
        labelRo: 'Sfeclă roșie',
        category: 'root_crop',
        group: 'Roots & Bulbs',
        priority: 2,
        commonInRomania: true,
        season: 'Spring–Autumn',
        sunlight: 'Full Sun',
        waterNeeds: 'Medium',
        rootDepth: 'Medium',
        perennial: false,
        guildRole: ['Producer'],
        ecologicalFunctions: ['Food production'],
        companionNotes: 'Good with onion, lettuce, cabbage family.',
    },
    {
        name: 'Radish',
        labelRo: 'Ridichi',
        category: 'root_crop',
        group: 'Roots & Bulbs',
        priority: 2,
        commonInRomania: true,
        season: 'Spring–Autumn',
        sunlight: 'Full Sun',
        waterNeeds: 'Medium',
        rootDepth: 'Shallow',
        perennial: false,
        guildRole: ['Producer'],
        ecologicalFunctions: ['Quick crop', 'Food production'],
        companionNotes: 'Good quick crop between slower plants.',
    },
    {
        name: 'Onion',
        labelRo: 'Ceapă',
        category: 'bulb',
        group: 'Roots & Bulbs',
        priority: 1,
        commonInRomania: true,
        season: 'Spring–Summer',
        sunlight: 'Full Sun',
        waterNeeds: 'Low',
        rootDepth: 'Shallow',
        perennial: false,
        guildRole: ['Producer', 'Pest repellent'],
        ecologicalFunctions: ['Food production', 'Pest confusion'],
        companionNotes: 'Good with carrot, lettuce, tomato. Avoid beans and peas.',
    },
    {
        name: 'Garlic',
        labelRo: 'Usturoi',
        category: 'bulb',
        group: 'Roots & Bulbs',
        priority: 1,
        commonInRomania: true,
        season: 'Autumn–Summer',
        sunlight: 'Full Sun',
        waterNeeds: 'Low',
        rootDepth: 'Shallow',
        perennial: false,
        guildRole: ['Producer', 'Pest repellent'],
        ecologicalFunctions: ['Food production', 'Pest repellent'],
        companionNotes: 'Useful near fruit trees, roses, tomatoes, carrots.',
    },

    // ── Leafy Greens ──────────────────────────────────────────────────────────
    {
        name: 'Lettuce',
        labelRo: 'Salată verde',
        category: 'leafy_green',
        group: 'Leafy Greens',
        priority: 1,
        commonInRomania: true,
        season: 'Spring–Autumn',
        sunlight: 'Partial Shade',
        waterNeeds: 'Medium',
        rootDepth: 'Shallow',
        perennial: false,
        guildRole: ['Producer', 'Groundcover'],
        ecologicalFunctions: ['Food production', 'Soil cover'],
        companionNotes: 'Good under taller crops in partial shade.',
    },
    {
        name: 'Spinach',
        labelRo: 'Spanac',
        category: 'leafy_green',
        group: 'Leafy Greens',
        priority: 2,
        commonInRomania: true,
        season: 'Spring–Autumn',
        sunlight: 'Partial Shade',
        waterNeeds: 'Medium',
        rootDepth: 'Shallow',
        perennial: false,
        guildRole: ['Producer', 'Groundcover'],
        ecologicalFunctions: ['Food production', 'Cool-season crop'],
        companionNotes: 'Good before warm-season crops.',
    },
    {
        name: 'Cabbage',
        labelRo: 'Varză',
        category: 'leafy_green',
        group: 'Leafy Greens',
        priority: 1,
        commonInRomania: true,
        season: 'Summer–Autumn',
        sunlight: 'Full Sun',
        waterNeeds: 'Medium',
        rootDepth: 'Medium',
        perennial: false,
        guildRole: ['Producer'],
        ecologicalFunctions: ['Food production'],
        companionNotes: 'Good with dill, celery, onion, aromatic herbs. Use flowers to attract beneficial insects.',
    },

    // ── Herbs ─────────────────────────────────────────────────────────────────
    {
        name: 'Parsley',
        labelRo: 'Pătrunjel',
        category: 'herb',
        group: 'Herbs',
        priority: 1,
        commonInRomania: true,
        season: 'Spring–Autumn',
        sunlight: 'Partial Shade',
        waterNeeds: 'Medium',
        rootDepth: 'Medium',
        perennial: false,
        guildRole: ['Producer', 'Pollinator attractor'],
        ecologicalFunctions: ['Culinary herb', 'Beneficial insect support'],
        companionNotes: 'Common culinary herb; can support beneficial insects when flowering.',
    },
    {
        name: 'Dill',
        labelRo: 'Mărar',
        category: 'herb',
        group: 'Herbs',
        priority: 1,
        commonInRomania: true,
        season: 'Spring–Summer',
        sunlight: 'Full Sun',
        waterNeeds: 'Medium',
        rootDepth: 'Medium',
        perennial: false,
        guildRole: ['Producer', 'Pollinator attractor'],
        ecologicalFunctions: ['Culinary herb', 'Pollinator support'],
        companionNotes: 'Good with cabbage family and cucumber.',
    },
    {
        name: 'Lovage',
        labelRo: 'Leuștean',
        category: 'herb',
        group: 'Herbs',
        priority: 1,
        commonInRomania: true,
        season: 'Spring–Autumn',
        sunlight: 'Partial Shade',
        waterNeeds: 'Medium',
        rootDepth: 'Deep',
        perennial: true,
        guildRole: ['Producer', 'Dynamic accumulator'],
        ecologicalFunctions: ['Culinary herb', 'Perennial herb'],
        companionNotes: 'Very common in Romanian gardens; useful as a perennial herb patch.',
    },
    {
        name: 'Basil',
        labelRo: 'Busuioc',
        category: 'herb',
        group: 'Herbs',
        priority: 1,
        commonInRomania: true,
        season: 'Summer',
        sunlight: 'Full Sun',
        waterNeeds: 'Medium',
        rootDepth: 'Shallow',
        perennial: false,
        guildRole: ['Producer', 'Pest repellent', 'Pollinator attractor'],
        ecologicalFunctions: ['Culinary herb', 'Pollinator support'],
        companionNotes: 'Classic companion for tomatoes and peppers.',
    },
    {
        name: 'Thyme',
        labelRo: 'Cimbru',
        category: 'herb',
        group: 'Herbs',
        priority: 2,
        commonInRomania: true,
        season: 'Spring–Autumn',
        sunlight: 'Full Sun',
        waterNeeds: 'Low',
        rootDepth: 'Shallow',
        perennial: true,
        guildRole: ['Producer', 'Pest repellent', 'Pollinator attractor'],
        ecologicalFunctions: ['Culinary herb', 'Pollinator support', 'Drought-tolerant edge plant'],
        companionNotes: 'Good in dry sunny edges.',
    },
    {
        name: 'Summer Savory',
        labelRo: 'Cimbru de grădină / Satureja',
        category: 'herb',
        group: 'Herbs',
        priority: 2,
        commonInRomania: true,
        season: 'Summer',
        sunlight: 'Full Sun',
        waterNeeds: 'Low',
        rootDepth: 'Shallow',
        perennial: false,
        guildRole: ['Producer', 'Pest repellent'],
        ecologicalFunctions: ['Culinary herb', 'Companion plant'],
        companionNotes: 'Traditional companion for beans.',
    },
    {
        name: 'Mint',
        labelRo: 'Mentă',
        category: 'herb',
        group: 'Herbs',
        priority: 2,
        commonInRomania: true,
        season: 'Spring–Autumn',
        sunlight: 'Partial Shade',
        waterNeeds: 'Medium',
        rootDepth: 'Shallow',
        perennial: true,
        guildRole: ['Producer', 'Pollinator attractor'],
        ecologicalFunctions: ['Culinary herb', 'Pollinator support'],
        companionNotes: 'Invasive. Prefer container or controlled area.',
    },
    {
        name: 'Sage',
        labelRo: 'Salvie',
        category: 'herb',
        group: 'Herbs',
        priority: 3,
        commonInRomania: true,
        season: 'Spring–Autumn',
        sunlight: 'Full Sun',
        waterNeeds: 'Low',
        rootDepth: 'Medium',
        perennial: true,
        guildRole: ['Producer', 'Pollinator attractor', 'Pest repellent'],
        ecologicalFunctions: ['Culinary herb', 'Medicinal', 'Pollinator support'],
        companionNotes: 'Good dry sunny perennial herb.',
    },

    // ── Flowers & Beneficials ─────────────────────────────────────────────────
    {
        name: 'Marigold',
        labelRo: 'Crăițe / Tagetes',
        category: 'flower',
        group: 'Flowers & Beneficials',
        priority: 1,
        commonInRomania: true,
        season: 'Summer–Autumn',
        sunlight: 'Full Sun',
        waterNeeds: 'Low',
        rootDepth: 'Shallow',
        perennial: false,
        guildRole: ['Pest repellent', 'Pollinator attractor'],
        ecologicalFunctions: ['Pest confusion', 'Pollinator support'],
        companionNotes: 'Useful near tomatoes, peppers, cabbage family, and beds.',
    },
    {
        name: 'Calendula',
        labelRo: 'Gălbenele',
        category: 'flower',
        group: 'Flowers & Beneficials',
        priority: 1,
        commonInRomania: true,
        season: 'Spring–Autumn',
        sunlight: 'Full Sun',
        waterNeeds: 'Low',
        rootDepth: 'Shallow',
        perennial: false,
        guildRole: ['Pollinator attractor', 'Medicinal'],
        ecologicalFunctions: ['Pollinator support', 'Medicinal', 'Self-seeding'],
        companionNotes: 'Excellent general companion flower.',
    },
    {
        name: 'Lavender',
        labelRo: 'Lavandă',
        category: 'herb',
        group: 'Flowers & Beneficials',
        priority: 2,
        commonInRomania: true,
        season: 'Summer',
        sunlight: 'Full Sun',
        waterNeeds: 'Low',
        rootDepth: 'Medium',
        perennial: true,
        guildRole: ['Pollinator attractor', 'Pest repellent'],
        ecologicalFunctions: ['Pollinator support', 'Aromatic border', 'Drought tolerant'],
        companionNotes: 'Good sunny border plant; prefers well-drained soil.',
    },
    {
        name: 'Borage',
        labelRo: 'Limba mielului',
        category: 'flower',
        group: 'Flowers & Beneficials',
        priority: 3,
        commonInRomania: false,
        season: 'Summer',
        sunlight: 'Full Sun',
        waterNeeds: 'Medium',
        rootDepth: 'Medium',
        perennial: false,
        guildRole: ['Pollinator attractor', 'Dynamic accumulator'],
        ecologicalFunctions: ['Pollinator support', 'Beneficial insect support'],
        companionNotes: 'Useful around strawberries, tomatoes, cucumbers, and squash.',
    },

    // ── Permaculture Support ──────────────────────────────────────────────────
    {
        name: 'Comfrey',
        labelRo: 'Tătăneasă',
        category: 'dynamic_accumulator',
        group: 'Permaculture Support',
        priority: 2,
        commonInRomania: true,
        season: 'Spring–Autumn',
        sunlight: 'Full Sun',
        waterNeeds: 'Medium',
        rootDepth: 'Deep',
        perennial: true,
        guildRole: ['Dynamic accumulator', 'Mulch plant'],
        ecologicalFunctions: ['Mulch biomass', 'Nutrient cycling', 'Pollinator support'],
        companionNotes: 'Excellent near fruit trees, but should be placed carefully because it is hard to remove.',
    },
    {
        name: 'Clover',
        labelRo: 'Trifoi',
        category: 'cover_crop',
        group: 'Permaculture Support',
        priority: 2,
        commonInRomania: true,
        season: 'Spring–Autumn',
        sunlight: 'Full Sun',
        waterNeeds: 'Medium',
        rootDepth: 'Shallow',
        perennial: true,
        guildRole: ['Nitrogen fixer', 'Groundcover'],
        ecologicalFunctions: ['Nitrogen fixation', 'Soil cover', 'Pollinator support'],
        companionNotes: 'Good living mulch and orchard groundcover.',
    },

    // ── Fruit Trees & Shrubs ──────────────────────────────────────────────────
    {
        name: 'Apple',
        labelRo: 'Măr',
        category: 'tree',
        group: 'Fruit Trees & Shrubs',
        priority: 1,
        commonInRomania: true,
        season: 'Perennial',
        sunlight: 'Full Sun',
        waterNeeds: 'Medium',
        rootDepth: 'Deep',
        perennial: true,
        guildRole: ['Producer', 'Canopy'],
        ecologicalFunctions: ['Fruit production', 'Canopy layer'],
        companionNotes: 'Good with comfrey, clover, garlic, calendula, yarrow.',
    },
    {
        name: 'Pear',
        labelRo: 'Păr',
        category: 'tree',
        group: 'Fruit Trees & Shrubs',
        priority: 1,
        commonInRomania: true,
        season: 'Perennial',
        sunlight: 'Full Sun',
        waterNeeds: 'Medium',
        rootDepth: 'Deep',
        perennial: true,
        guildRole: ['Producer', 'Canopy'],
        ecologicalFunctions: ['Fruit production', 'Canopy layer'],
        companionNotes: 'Good with comfrey, clover, aromatic herbs, and pollinator flowers.',
    },
    {
        name: 'Plum',
        labelRo: 'Prun',
        category: 'tree',
        group: 'Fruit Trees & Shrubs',
        priority: 1,
        commonInRomania: true,
        season: 'Perennial',
        sunlight: 'Full Sun',
        waterNeeds: 'Medium',
        rootDepth: 'Deep',
        perennial: true,
        guildRole: ['Producer', 'Canopy'],
        ecologicalFunctions: ['Fruit production', 'Canopy layer'],
        companionNotes: 'Very common Romanian fruit tree; good in orchard/guild layouts.',
    },
    {
        name: 'Cherry',
        labelRo: 'Cireș',
        category: 'tree',
        group: 'Fruit Trees & Shrubs',
        priority: 1,
        commonInRomania: true,
        season: 'Perennial',
        sunlight: 'Full Sun',
        waterNeeds: 'Medium',
        rootDepth: 'Deep',
        perennial: true,
        guildRole: ['Producer', 'Canopy'],
        ecologicalFunctions: ['Fruit production', 'Canopy layer'],
        companionNotes: 'Good with pollinator flowers and low-competition groundcovers.',
    },
    {
        name: 'Sour Cherry',
        labelRo: 'Vișin',
        category: 'tree',
        group: 'Fruit Trees & Shrubs',
        priority: 2,
        commonInRomania: true,
        season: 'Perennial',
        sunlight: 'Full Sun',
        waterNeeds: 'Medium',
        rootDepth: 'Deep',
        perennial: true,
        guildRole: ['Producer', 'Canopy'],
        ecologicalFunctions: ['Fruit production', 'Canopy layer'],
        companionNotes: 'Traditional Romanian fruit tree.',
    },
    {
        name: 'Walnut',
        labelRo: 'Nuc',
        category: 'tree',
        group: 'Fruit Trees & Shrubs',
        priority: 2,
        commonInRomania: true,
        season: 'Perennial',
        sunlight: 'Full Sun',
        waterNeeds: 'Low',
        rootDepth: 'Deep',
        perennial: true,
        guildRole: ['Producer', 'Canopy'],
        ecologicalFunctions: ['Nut production', 'Shade', 'Canopy layer'],
        companionNotes: 'Use carefully because walnut can suppress some nearby plants.',
    },
    {
        name: 'Hazelnut',
        labelRo: 'Alun',
        category: 'shrub',
        group: 'Fruit Trees & Shrubs',
        priority: 2,
        commonInRomania: true,
        season: 'Perennial',
        sunlight: 'Full Sun',
        waterNeeds: 'Medium',
        rootDepth: 'Medium',
        perennial: true,
        guildRole: ['Producer', 'Shrub layer'],
        ecologicalFunctions: ['Nut production', 'Hedge', 'Windbreak'],
        companionNotes: 'Good as edible hedge or orchard edge.',
    },
    {
        name: 'Fig',
        labelRo: 'Smochin',
        category: 'tree',
        group: 'Fruit Trees & Shrubs',
        priority: 3,
        commonInRomania: true,
        season: 'Perennial',
        sunlight: 'Full Sun',
        waterNeeds: 'Low',
        rootDepth: 'Medium',
        perennial: true,
        guildRole: ['Producer', 'Shrub layer'],
        ecologicalFunctions: ['Fruit production', 'Drought tolerance'],
        companionNotes: 'Best in warm/protected microclimates.',
    },
    {
        name: 'Grape',
        labelRo: 'Viță de vie',
        category: 'vine',
        group: 'Fruit Trees & Shrubs',
        priority: 1,
        commonInRomania: true,
        season: 'Perennial',
        sunlight: 'Full Sun',
        waterNeeds: 'Low',
        rootDepth: 'Deep',
        perennial: true,
        guildRole: ['Producer', 'Climber'],
        ecologicalFunctions: ['Fruit production', 'Vertical layer'],
        companionNotes: 'Needs support/trellis and good airflow.',
    },
    {
        name: 'Strawberry',
        labelRo: 'Căpșuni',
        category: 'groundcover',
        group: 'Fruit Trees & Shrubs',
        priority: 1,
        commonInRomania: true,
        season: 'Spring–Summer',
        sunlight: 'Full Sun',
        waterNeeds: 'Medium',
        rootDepth: 'Shallow',
        perennial: true,
        guildRole: ['Producer', 'Groundcover'],
        ecologicalFunctions: ['Fruit production', 'Living mulch'],
        companionNotes: 'Good with borage, garlic, onion, lettuce.',
    },
    {
        name: 'Raspberry',
        labelRo: 'Zmeur',
        category: 'shrub',
        group: 'Fruit Trees & Shrubs',
        priority: 1,
        commonInRomania: true,
        season: 'Summer',
        sunlight: 'Full Sun',
        waterNeeds: 'Medium',
        rootDepth: 'Medium',
        perennial: true,
        guildRole: ['Producer', 'Shrub layer'],
        ecologicalFunctions: ['Fruit production', 'Shrub layer'],
        companionNotes: 'Good in berry patch rows or edge systems.',
    },
    {
        name: 'Blackberry',
        labelRo: 'Mur',
        category: 'shrub',
        group: 'Fruit Trees & Shrubs',
        priority: 2,
        commonInRomania: true,
        season: 'Summer',
        sunlight: 'Full Sun',
        waterNeeds: 'Medium',
        rootDepth: 'Medium',
        perennial: true,
        guildRole: ['Producer', 'Shrub layer'],
        ecologicalFunctions: ['Fruit production', 'Hedge'],
        companionNotes: 'Good as productive edge, but manage spread.',
    },
    {
        name: 'Currant',
        labelRo: 'Coacăz',
        category: 'shrub',
        group: 'Fruit Trees & Shrubs',
        priority: 2,
        commonInRomania: true,
        season: 'Summer',
        sunlight: 'Partial Shade',
        waterNeeds: 'Medium',
        rootDepth: 'Medium',
        perennial: true,
        guildRole: ['Producer', 'Shrub layer'],
        ecologicalFunctions: ['Fruit production', 'Shrub layer'],
        companionNotes: 'Good in partial shade or orchard edge.',
    },
];

export const MAIN_CROP_NAMES_ROMANIA = MAIN_CROPS_ROMANIA.map(p => p.name);

export const MAIN_CROP_GROUPS_ROMANIA = [
    'Vegetables',
    'Roots & Bulbs',
    'Leafy Greens',
    'Herbs',
    'Flowers & Beneficials',
    'Permaculture Support',
    'Fruit Trees & Shrubs',
];

export function getMainCropsByGroup(group) {
    return MAIN_CROPS_ROMANIA.filter(p => p.group === group);
}

export function getPriorityMainCrops(limit = 20) {
    return [...MAIN_CROPS_ROMANIA]
        .sort((a, b) => a.priority - b.priority || a.name.localeCompare(b.name))
        .slice(0, limit);
}
