import mongoose from 'mongoose';
import fs from 'fs';
import path from 'path';
import dotenv from 'dotenv';
import Plant from './models/plantModel.js';

dotenv.config();
await mongoose.connect(process.env.MONGODB_URI);


// Helper to load and convert SVG to base64
const getIconBase64 = (filename) => {
    const filePath = path.join('../fixed-frontend/src/assets/veg-icons', filename);

    const svgData = fs.readFileSync(filePath);
    return Buffer.from(svgData).toString('base64');
};


const plants = [
    {
        name: 'Basil',
        sunlight: 'Full Sun',
        season: 'Summer',
        note: 'Good with tomatoes; repels mosquitoes and flies.',
        iconData: getIconBase64('basil.svg'),
        featured: true,
    },
    {
        name: 'Tomato',
        sunlight: 'Full Sun',
        season: 'Spring–Fall',
        note: 'Good with basil, carrots, and marigolds. Avoid planting near corn or potatoes.',
        iconData: getIconBase64('tomato.svg'),
        featured: true,
    },
    {
        name: 'Carrot',
        sunlight: 'Full Sun',
        season: 'Spring–Fall',
        note: 'Does well with tomatoes, onions, and lettuce. Avoid dill and parsnips.',
        iconData: getIconBase64('carrot.svg'),
        featured: true,
    },
    {
        name: 'Parsley',
        sunlight: 'Full Sun',
        season: 'Summer',
        note: 'Good with tomatoes, asparagus, and corn. Keep away from lettuce.',
        iconData: getIconBase64('parsley.svg'),
    },
    {
        name: 'Lettuce',
        sunlight: 'Partial Shade',
        season: 'Spring–Fall',
        note: 'Companion to carrots, radishes, and strawberries. Avoid planting near parsley.',
        iconData: getIconBase64('lettuce.svg'),
    },
    {
        name: 'Sunflower',
        sunlight: 'Full Sun',
        season: 'Summer',
        note: 'Attracts pollinators. Can be allelopathic — avoid near potatoes or beans.',
        iconData: getIconBase64('sunflower.svg'),
    },
    {
        name: 'Zucchini',
        sunlight: 'Full Sun',
        season: 'Summer',
        note: 'Likes beans, corn, and nasturtiums. Avoid potatoes.',
        iconData: getIconBase64('zucchini.svg'),
    },
    {
        name: 'Cucumber',
        sunlight: 'Full Sun',
        season: 'Summer',
        note: 'Grows well with beans, peas, and radishes. Avoid aromatic herbs.',
        iconData: getIconBase64('cucumber.svg'),
    },
    {
        name: 'Onion',
        sunlight: 'Full Sun',
        season: 'Spring–Fall',
        note: 'Good with carrots, beets, and lettuce. Avoid peas and beans.',
        iconData: getIconBase64('onion.svg'),
        featured: true,
    },
    {
        name: 'Radish',
        sunlight: 'Full Sun',
        season: 'Spring–Fall',
        note: 'Good with lettuce, carrots, and cucumbers. Helps deter pests.',
        iconData: getIconBase64('radish.svg'),
    },
    {
        name: 'Strawberry',
        sunlight: 'Full Sun',
        season: 'Spring–Summer',
        note: 'Plant with lettuce and spinach; avoid cabbage.',
        iconData: getIconBase64('strawberry.svg'),

    },
    {
        name: 'Tarragon',
        sunlight: 'Full Sun',
        season: 'Summer',
        note: 'Not known for companions but repels pests and thrives near most plants.',
        iconData: getIconBase64('tarragon.svg'),
    },
    {
        name: 'Thyme',
        sunlight: 'Full Sun',
        season: 'Spring–Fall',
        note: 'Good with cabbage and tomatoes. Repels pests.',
        iconData: getIconBase64('thyme.svg'),
    },
    {
        name: 'Tulip',
        sunlight: 'Full Sun',
        season: 'Spring',
        note: 'Ornamental bulb. Avoid near edibles due to potential allelopathy.',
        iconData: getIconBase64('tulip.svg'),
    },
    {
        name: 'Walnut',
        sunlight: 'Full Sun',
        season: 'Fall',
        note: 'Allelopathic: avoid planting near most vegetables and fruits.',
        iconData: getIconBase64('walnut.svg'),
    },
    {
        name: 'Watermelon',
        sunlight: 'Full Sun',
        season: 'Summer',
        note: 'Companions: corn and nasturtium. Needs space and pollinators.',
        iconData: getIconBase64('watermelon.svg'),
    },
    {
        name: 'Wheat',
        sunlight: 'Full Sun',
        season: 'Spring–Fall',
        note: 'Can be grown with legumes to enrich soil nitrogen.',
        iconData: getIconBase64('wheat.svg'),
    },
    {
        name: 'Zinnia',
        sunlight: 'Full Sun',
        season: 'Summer–Fall',
        note: 'Attracts pollinators; excellent near vegetables.',
        iconData: getIconBase64('zinnia.svg'),
    },
    {
        name: 'Apple',
        sunlight: 'Full Sun',
        season: 'Fall',
        note: 'Avoid near walnut trees. Companion: garlic and chives to deter pests.',
        iconData: getIconBase64('apple.svg'),
    },
    {
        name: 'Apricot',
        sunlight: 'Full Sun',
        season: 'Summer',
        note: 'Plant away from shade; companions include lavender and chives.',
        iconData: getIconBase64('apricot.svg'),
    },
    {
        name: 'Asparagus',
        sunlight: 'Full Sun',
        season: 'Spring',
        note: 'Likes tomatoes and parsley. Avoid onions and garlic.',
        iconData: getIconBase64('asparagus.svg'),
    },
    {
        name: 'Beans',
        sunlight: 'Full Sun',
        season: 'Summer',
        note: 'Likes corn and cucumbers. Avoid onions and garlic.',
        iconData: getIconBase64('beans.svg'),
    },
    {
        name: 'Beetroot',
        sunlight: 'Full Sun',
        season: 'Spring–Fall',
        note: 'Good with onions and lettuce. Avoid pole beans.',
        iconData: getIconBase64('beetroot.svg'),
    },
    {
        name: 'Bell Pepper',
        sunlight: 'Full Sun',
        season: 'Summer',
        note: 'Good with basil and onions. Avoid beans.',
        iconData: getIconBase64('bell-pepper.svg'),
        featured: true,
    },
    {
        name: 'Blackberry',
        sunlight: 'Full Sun',
        season: 'Summer',
        note: 'Avoid nightshades nearby. Requires spacing.',
        iconData: getIconBase64('blackberry.svg'),
    },
    {
        name: 'Blueberry',
        sunlight: 'Full Sun',
        season: 'Summer',
        note: 'Prefers acidic soil. Good with thyme and strawberries.',
        iconData: getIconBase64('blueberry.svg'),
    },
    {
        name: 'Broccoli',
        sunlight: 'Full Sun',
        season: 'Cool season',
        note: 'Good with dill, onion, and celery. Avoid strawberries.',
        iconData: getIconBase64('broccoli.svg'),
    },
    {
        name: 'Cabbage',
        sunlight: 'Full Sun',
        season: 'Spring or Fall',
        note: 'Companions: dill, onion, chamomile. Avoid strawberries and tomatoes.',
        iconData: getIconBase64('cabbage.svg'),
    },
    {
        name: 'Calendula',
        sunlight: 'Full Sun',
        season: 'Spring–Fall',
        note: 'Attracts pollinators. Good with almost all vegetables.',
        iconData: getIconBase64('calendula.svg'),
    },
    {
        name: 'Cauliflower',
        sunlight: 'Full Sun',
        season: 'Spring–Fall',
        note: 'Likes dill and sage. Avoid strawberries.',
        iconData: getIconBase64('cauliflower.svg'),
    },
    {
        name: 'Celery',
        sunlight: 'Full Sun',
        season: 'Cool season',
        note: 'Good with cabbage, onions, and tomatoes.',
        iconData: getIconBase64('celery.svg'),
    },
    {
        name: 'Cherry',
        sunlight: 'Full Sun',
        season: 'Spring–Summer',
        note: 'Avoid black walnut. Good with chives and garlic for pest deterrence.',
        iconData: getIconBase64('cherry-svgrepo-com.svg'),
    },
    {
        name: 'Cherry Tomatoes',
        sunlight: 'Full Sun',
        season: 'Summer',
        note: 'Same companions as standard tomatoes: basil, marigold.',
        iconData: getIconBase64('cherry-tomatoes.svg'),
    },
    {
        name: 'Coriander',
        sunlight: 'Full Sun',
        season: 'Spring–Fall',
        note: 'Likes spinach and basil. Deters aphids.',
        iconData: getIconBase64('coriander.svg'),
    },
    {
        name: 'Corn',
        sunlight: 'Full Sun',
        season: 'Summer',
        note: 'Great with beans and squash (Three Sisters). Avoid tomatoes.',
        iconData: getIconBase64('corn.svg'),
    },
    {
        name: 'Cranberry',
        sunlight: 'Full Sun',
        season: 'Fall',
        note: 'Acid-loving groundcover. Avoid heavy feeders nearby.',
        iconData: getIconBase64('cranberry.svg'),
    },
    {
        name: 'Dill',
        sunlight: 'Full Sun',
        season: 'Summer',
        note: 'Great with cabbage and cucumbers. Avoid carrots.',
        iconData: getIconBase64('dill.svg'),
    },
    {
        name: 'Eggplant',
        sunlight: 'Full Sun',
        season: 'Summer',
        note: 'Likes beans, thyme, and marigold. Avoid fennel.',
        iconData: getIconBase64('eggplant.svg'),

    },
    {
        name: 'Elderberry',
        sunlight: 'Full Sun',
        season: 'Late Summer',
        note: 'Avoid near onions or garlic. Attracts birds.',
        iconData: getIconBase64('elderberry.svg'),
    },
    {
        name: 'Fig',
        sunlight: 'Full Sun',
        season: 'Summer–Fall',
        note: 'Avoid deep-rooted plants nearby. Likes herbs like oregano.',
        iconData: getIconBase64('fig-svgrepo-com.svg'),
    },
    {
        name: 'Garlic',
        sunlight: 'Full Sun',
        season: 'Fall–Spring',
        note: 'Deter pests. Good with roses, carrots, and apple trees.',
        iconData: getIconBase64('garlic.svg'),

    },
    {
        name: 'Grape',
        sunlight: 'Full Sun',
        season: 'Late Summer',
        note: 'Avoid cabbage family nearby. Plant with chives or garlic.',
        iconData: getIconBase64('grape.svg'),
    },
    {
        name: 'Hazelnut',
        sunlight: 'Full Sun',
        season: 'Fall',
        note: 'Best planted away from vegetables. Needs companion tree.',
        iconData: getIconBase64('hazelnut.svg'),
    },
    {
        name: 'Hot Pepper',
        sunlight: 'Full Sun',
        season: 'Summer',
        note: 'Likes basil and carrots. Avoid beans.',
        iconData: getIconBase64('hot-pepper.svg'),
    },
    {
        name: 'Lavender',
        sunlight: 'Full Sun',
        season: 'Summer',
        note: 'Good with rosemary and thyme. Repels pests.',
        iconData: getIconBase64('lavender.svg'),
    },
    {
        name: 'Leek',
        sunlight: 'Full Sun',
        season: 'Cool season',
        note: 'Plant with carrots, celery, and beets.',
        iconData: getIconBase64('leek.svg'),
    },
    {
        name: 'Lovage',
        sunlight: 'Full Sun',
        season: 'Spring–Fall',
        note: 'Improves growth of nearby plants. Attracts beneficial insects.',
        iconData: getIconBase64('lovage.svg'),
    },
    {
        name: 'Nasturium',
        sunlight: 'Full Sun',
        season: 'Summer',
        note: 'Great trap crop. Plant near cucumbers, squash, and tomatoes.',
        iconData: getIconBase64('nasturium.svg'),
    },
    {
        name: 'Nectarin',
        sunlight: 'Full Sun',
        season: 'Summer',
        note: 'Good with garlic and chives. Prone to aphids without companions.',
        iconData: getIconBase64('nectarin.svg'),
    },
    {
        name: 'Oregano',
        sunlight: 'Full Sun',
        season: 'Spring–Fall',
        note: 'Repels pests. Good under tomatoes and peppers.',
        iconData: getIconBase64('oregano.svg'),
    },
    {
        name: 'Parsnip',
        sunlight: 'Full Sun',
        season: 'Fall–Winter',
        note: 'Avoid planting near carrots. Likes onions and legumes.',
        iconData: getIconBase64('parsnip.svg'),
    },
    {
        name: 'Peach',
        sunlight: 'Full Sun',
        season: 'Summer',
        note: 'Avoid planting near tomatoes. Likes garlic nearby.',
        iconData: getIconBase64('peach.svg'),
    },
    {
        name: 'Pear',
        sunlight: 'Full Sun',
        season: 'Fall',
        note: 'Plant with chives and comfrey. Avoid walnut trees.',
        iconData: getIconBase64('pear.svg'),
    },
    {
        name: 'Peas',
        sunlight: 'Full Sun',
        season: 'Spring',
        note: 'Likes carrots and turnips. Avoid onions and garlic.',
        iconData: getIconBase64('peas.svg'),
    },
    {
        name: 'Peppermint',
        sunlight: 'Partial Shade',
        season: 'Spring–Fall',
        note: 'Repels pests. Contain its spread when near vegetables.',
        iconData: getIconBase64('peppermint.svg'),
    },
    {
        name: 'Petunia',
        sunlight: 'Full Sun',
        season: 'Summer',
        note: 'Repels aphids and asparagus beetles. Good ornamental near crops.',
        iconData: getIconBase64('petunia.svg'),
    },
    {
        name: 'Plum',
        sunlight: 'Full Sun',
        season: 'Summer',
        note: 'Likes garlic and onions nearby to deter borers.',
        iconData: getIconBase64('plum.svg'),
    },
    {
        name: 'Potatoes',
        sunlight: 'Full Sun',
        season: 'Spring–Summer',
        note: 'Avoid tomatoes and cucumbers. Good with beans and cabbage.',
        iconData: getIconBase64('potatoes.svg'),
    },
    {
        name: 'Pumpkin',
        sunlight: 'Full Sun',
        season: 'Fall',
        note: 'Plant with corn and beans. Needs space to sprawl.',
        iconData: getIconBase64('pumpkin.svg'),
    },
    {
        name: 'Quince',
        sunlight: 'Full Sun',
        season: 'Fall',
        note: 'Not picky. Likes most herbs around its base.',
        iconData: getIconBase64('quince.svg'),
    },
    {
        name: 'Raspberry',
        sunlight: 'Full Sun',
        season: 'Summer',
        note: 'Avoid potatoes and tomatoes. Likes garlic and chives.',
        iconData: getIconBase64('raspberry.svg'),
    },
    {
        name: 'Rose',
        sunlight: 'Full Sun',
        season: 'Spring–Fall',
        note: 'Plant with garlic and chives to deter aphids.',
        iconData: getIconBase64('rose.svg'),
    },
    {
        name: 'Rosemary',
        sunlight: 'Full Sun',
        season: 'Year-round (mild climates)',
        note: 'Repels pests. Great near cabbage and beans.',
        iconData: getIconBase64('rosemary.svg'),
    },
    {
        name: 'Sage',
        sunlight: 'Full Sun',
        season: 'Spring–Fall',
        note: 'Good with rosemary and carrots. Avoid cucumbers.',
        iconData: getIconBase64('sage.svg'),
    },
    {
        name: 'Sour Cherry',
        sunlight: 'Full Sun',
        season: 'Summer',
        note: 'Plant with garlic and nasturtiums for pest control.',
        iconData: getIconBase64('sourcherry.svg'),
    },
];

await Plant.deleteMany();
await Plant.insertMany(plants);
console.log('Plants with icons seeded.');
process.exit();
